language: generic
sudo: required
services:
  - docker

before_script:
 - echo $DOCKER_USERNAME
 - echo $DOCKER_PASSWORD
## build image for test
before_install:
  - docker build -t faizanmalik/react-test -f ./client/Dockerfile.dev ./client/

## run test
script:
  - docker run -e CI=true faizanmalik/react-test npm test

after_success:
  - docker build -t faizanmalik/multi-client ./client
  - docker build -t faizanmalik/multi-nginx ./nginx
  - docker build -t faizanmalik/multi-server ./server
  - docker build -t faizanmalik/multi-worker ./worker
  ## login into docker cli
  - docker login -u $(echo $DOCKER_USERNAME) -p $(echo $DOCKER_PASSWORD)
  ## Upload these image to docker hub
  - docker push faizanmalik/multi-client
  - docker push faizanmalik/multi-nginx
  - docker push faizanmalik/multi-server
  - docker push faizanmalik/multi-worker

on:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker-app'
  env: 'Multidockerapp-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-037346945350'
  bucket_path: 'multi-docker-app'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY